services:
  api:
    restart: always
    labels:
      - "traefik.http.routers.api-router.rule=Host(`${HOST}`)"
      - "traefik.http.routers.api-router.tls=true"

  db:
    restart: always

  web:
    restart: always
    labels:
      - "traefik.http.routers.web-router.rule=Host(`${HOST}`)"
      - "traefik.http.routers.web-router.tls=true"
  
  traefik:
    restart: always
    command:
      - "--providers.docker.exposedByDefault=false"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=acme.json"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--entrypoints.websecure.http.tls.certresolver=letsencrypt"
    ports:
      - "443:443"
