services:
  api:
    build:
      context: ./backends/api
      target: base
    command: npm run start:dev
    volumes:
      - ./backends/api/src:/app/src
      - ./backends/api/prisma:/app/prisma
    ports:
      - ${API_PORT}:${API_PORT}

  db:
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
  